BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Fotografias] (
    [id] INT NOT NULL IDENTITY(1,1),
    [url_path] VARCHAR(1000) NOT NULL,
    [referencia] VARCHAR(20) NOT NULL,
    CONSTRAINT [PK__Fotograf__3213E83FDC1F08F3] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
